export const USER_CHANGE_STATE="USER_CHANGE_STATE"
export const CURRENT_ACCOUNT_CHANGE_STATE="CURRENT_ACCOUNT_CHANGE_STATE"
export const STUDENT_STATE="STUDENT_STATE"
export const STAFF_STATE="STAFF_STATE"
export const LOGOUT='LOGOUT'
export const LOGIN='LOGIN'
export const CLEAR_DATA="CLEAR_DATA"